### ISSUE TITLE
 Availability of the PolSAR Dataset

### ISSUE THREAD

**Issue by YangTze7** [ggsDing/SARSeg#1]
Hi,I'm interested in PolSAR segmentation but having trouble in acquiring dataset, and I cannot find download link on the 2020 Gaofen contest websites. Is the dataset still available now? Appreciate it if you could  give me some advice.

**Comment by DingLei14** [comment]
Unfortunately, this dataset was only open during the contest. I don't think I am allowed to release it. However, you can contact my email to discuss the access: lei.ding@unitn.it
